Optimize redundant logic used in queries
parse-community/parse-server pull request #7061
Opened 2020-12-12 05:35 UTC by pdiaz

After upgrading parse-server from 2.7.4 to 4.4.0 MongoDB 4.0 maxed CPU usage from what used to be barely 20% usage.

This does reduce the redundant complexity on queries that involve pointer permissions.

2020-12-12 06:57 UTC, dplewis commented
Thanks for the PR? Can you write a test case for this?

2020-12-12 09:53 UTC, mtrezza commented
Would you please also open an issue for this to explain the proposed change? This allow others to join the discussion more easily and helps us to better trace changes in Parse Server.

2020-12-12 12:30 UTC, mtrezza requested changes
Some minor comments

2020-12-12 12:30 UTC, mtrezza commented on CHANGELOG.md
> +- IMPROVE: Optimize queries on classes with pointer permissions.
Add: `[#7061](https://github.com/parse-community/parse-server/pull/7061). Thanks to [Pedro Diaz](https://github.com/pdiaz)`

You can remove your name of course if you prefer to do so.

2020-12-12 12:30 UTC, mtrezza commented on src/Controllers/DatabaseController.js
> +    if (query.$or.length === 1) return query.$or[0];
Can you please wrap the if block in brackets?

@dplewis Shouldn't lint currently enforce this? If not, I think we should add that rule; if blocks without brackets are just an unnecessary bug risk IMHO.

2020-12-12 12:30 UTC, mtrezza commented on src/Controllers/DatabaseController.js
> +
Please remove empty line.

2020-12-12 12:30 UTC, mtrezza commented on src/Controllers/DatabaseController.js
> +
Please remove empty line.

2020-12-13 04:43 UTC, dplewis requested changes
Just a few nits

2020-12-13 04:43 UTC, dplewis commented on src/Controllers/DatabaseController.js
> +      return query;
Can you add write test case for if `$or` doesn't exist?

2020-12-13 04:43 UTC, dplewis commented on src/Controllers/DatabaseController.js
> +      return query;
Can you add write test case for if `$and` doesn't exist?

2020-12-14 02:18 UTC, dplewis commented
Have you tried your branch in production?

2020-12-14 09:26 UTC, mtrezza commented
Before merging, mind any ongoing discussion in https://github.com/parse-community/parse-server/issues/7065.

2020-12-14 15:30 UTC, pdiaz commented
> Have you tried your branch in production or tested it against your large database?

Yes, after this optimization performance went back to the same range as before.

2020-12-14 15:33 UTC, dplewis approved these changes
LGTM! @mtrezza How does it look?

2020-12-14 15:37 UTC, mtrezza commented
I see that the test cases test the new methods of the database controller, but there is no high-level test case that tests whether these methods are implemented correctly within the controller. Can we add a test case that makes a Parse.Query and evaluates the optimized query that would be sent to the DB client?

2020-12-14 17:29 UTC, pdiaz commented
> I see that the test cases test the new reduction methods of the database controller, but there is no high-level test case that tests whether these methods are implemented correctly within the controller and in which scenarios they are actually applied to a query. Can we add some test cases that make a `ParseQuery` and ensure the optimization of the resulting query?

Good call! I previously tested only with two pointer permissions, so I added two extra test cases for 2 and 3 pointer permissions on a class and fixed and issue detected with the second case.

2020-12-14 18:03 UTC, mtrezza requested changes
Just trivia, but on a general note:

Does this optimization apply to all $or / $and across a query or only related pointer permissions?

2020-12-14 19:15 UTC, pdiaz commented on spec/DatabaseController.spec.js
> +
All empty lines? If not between what exactly?

2020-12-14 19:51 UTC, pdiaz commented
> Does this optimization apply to all $or / $and across a query or only related pointer permissions?

@mtrezza No all, only on find operations related to pointer permissions and not the queries themselves. Update operations could also have unoptimized $and operations.

A full optimizer for queries in general would require many more test cases.

2020-12-14 20:26 UTC, mtrezza commented
> A full optimizer for queries in general would require many more test cases.

I was thinking into that direction. A Parse Query Optimizer would be an interesting feature, but maybe that's more a job for the guys at MongoDB.

This PR looks good to me, ready for merge I'd say.

2020-12-14 20:40 UTC, pdiaz commented
> > A full optimizer for queries in general would require many more test cases.
> 
> I was thinking into that direction. A Parse Query Optimizer would be an interesting feature, but maybe that's more a job for the guys at MongoDB.
> 
> This PR looks good to me, ready for merge I'd say.

Leaving that task to MongoDB guys means that a MongoDB upgrade would be required for everybody and that would take even much longer. I've been already working on that idea in my own, it will take some time to be ready. 

This PR right now is already a good step forward.

2020-12-14 20:42 UTC, pdiaz commented
@mtrezza @dplewis Looks like PG tests are a bit flaky. Can you trigger a restart?

2020-12-14 20:58 UTC, mtrezza commented
Checks passed. @dplewis any thoughts before merging?

2020-12-16 05:41 UTC, merged

2021-11-01 16:36 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

2022-03-14 13:08 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)