New: Validate Cloud Validators
parse-community/parse-server pull request #7154
Opened 2021-01-31 13:20 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Adds a cloud validator validator to make sure that cloud validators are formatted correctly.

Related issue: #7153

### Approach

Validates when a new trigger is created.

### TODOs before merging

- [x] Add test cases
- [ ] Add entry to changelog

2021-02-09 08:44 UTC, davimacedo reviewed
Do you think it would be possible to also add at least one test case to make sure that nothing logs in when the configuration is valid?

2021-02-09 09:09 UTC, dblythy commented
Good call, added in

2021-02-09 17:41 UTC, davimacedo approved these changes
LGTM!

2021-02-21 06:21 UTC, dblythy commented
Needs to include new validator options `requireAllRoles` `requireAnyRoles`

2021-02-23 13:48 UTC, mtrezza requested changes

2021-02-23 13:48 UTC, mtrezza commented on CHANGELOG.md
> +- IMPROVE: Cloud Validators will now log on invalid configuration [#7154](https://github.com/parse-community/parse-server/pull/7154). Thanks to [dblythy](https://github.com/dblythy)
I have seen multiple names for this feature so far:
- cloud function validation
- Cloud Validators
- Parse.Cloud validator

Let's find a consistent name; it is validating `Cloud Functions` that are part of `Cloud Code`; in the docs this is already titled "cloud function validation", so let's stick with `Cloud Function validation`. How about:

> - IMPROVE: Log error on invalid Cloud Function validation configuration.

2021-02-23 13:49 UTC, mtrezza commented
Why is a failed validation only logging an error (that can be easily overseen) and not throwing an error on server start? I assume that in usual cases, validation configuration is not dynamically defined but statically defined once on server start.

2021-02-23 16:44 UTC, mtrezza commented
Well, thanks for reacting so fast in changing to throwing, but I actually wanted to start a discussion about it to find a solution. What's your opinion on that?

2021-02-23 16:51 UTC, dblythy commented
Sorry @mtrezza I’d thought that I’d replied to you. 

I didn’t realise that you meant a class to validate the Parse Server options as well. I think that’s a good idea and will make it a lot easier to add new features. 

I think throwing the error makes sense. The only concern is that it might break some configurations if they’ve accidentally mistyped a field.

2021-02-23 16:54 UTC, mtrezza commented
I agree that a generic config validation doesn't have to be in this PR.

> The only concern is that it might break some configurations if they’ve accidentally mistyped a field.

Isn't mistyping one of the reasons why we'd want to throw?

2021-02-24 01:34 UTC, dblythy commented
I mean that I would break existing configurations that have a mistyped key. It would effectively be a “breaking change”.

2021-02-24 02:22 UTC, mtrezza commented
Introducing validation is not a breaking change as we do not assume misconfiguration as the basis reference to determine what constitutes a breaking change.

In other words, a misconfiguration is a developer bug, to which the same considerations apply as to a repository bug, which is also not assumed to be a basis reference to determine what constitutes a breaking change.

2021-03-01 23:28 UTC, mtrezza commented
@dblythy Would you merge current master to get the tests to pass?

2021-03-01 23:41 UTC, mtrezza commented
@dblythy Do you think this PR is ready, or anything you want to add?

2021-03-01 23:42 UTC, mtrezza approved these changes
LGTM

2021-03-01 23:47 UTC, dblythy commented
> @dblythy Do you think this PR is ready, or anything you want to add?

I'm happy with it, thanks Manuel 😊

2021-03-01 23:52 UTC, merged

2021-03-01 23:52 UTC, mtrezza commented
Great!

2021-11-01 16:32 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

2022-03-14 13:04 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)