describe how to use forked parse-server in custom docker image
parse-community/parse-server pull request #7206
Opened 2021-02-18 11:45 UTC by mman

### New Pull Request Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).

### Issue Description
I am trying to improve the wording around how to run a custom forked version of parse-server via docker, so that feature branches and bug fixes can be tested in the staging/dev environments before creating a pull request.

- [x ] Add changes to documentation (guides, repository pages, in-code descriptions)

2021-02-18 12:29 UTC, mtrezza approved these changes
Thanks for adding this! Just a nit..

2021-02-18 12:29 UTC, mtrezza commented on CONTRIBUTING.md
> +* The `npm run prepare` step is automatically invoked when your package depends on forked parse-server installed via git for example using `npm install --save git+https://github.com/MY_USERNAME/parse
To not reference a potentially real GitHub user here, please change to:

> * The `npm run prepare` step is automatically invoked when your package depends on forked parse-server installed via git for example using `npm install --save git+https://github.com/[username]/parse-server#[branch/commit]`.

2021-02-18 12:29 UTC, mtrezza commented on CONTRIBUTING.md
> +*Answer*: In your `package.json`, update the `parse-server` dependency to `https://github.com/MY_USERNAME/parse-server#MY_FEATURE`. Make sure the `npm install` step in your `Dockerfile` is running un
To not reference a potentially real GitHub user here, please change to:

`https://github.com/[username]/parse-server#[branch/commit]`

2021-02-18 12:30 UTC, mtrezza requested changes
I meant to request the changes I mentioned earlier.

2021-02-18 14:17 UTC, mtrezza approved these changes
Thanks for his PR!

2021-02-18 18:22 UTC, davimacedo approved these changes

2021-02-18 19:03 UTC, merged

2021-11-01 16:33 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

2022-03-14 13:05 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)