Fix Twitter API Oauth Error
parse-community/parse-server pull request #7370
Opened 2021-04-24 01:15 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Fixes the failing test explained in #7369.

### Approach

Changes the endpoint that the GET request makes from https://api.twitter.com/1.1/help/configuration.json to https://api.twitter.com/1.1/oauth/request_token.

2021-04-24 10:52 UTC, mtrezza commented
Thanks for opening this PR!

That is interesting, did you find any reference in the Twitter docs why this has changes?

2021-04-24 15:47 UTC, dblythy commented
Hey @mtrezza, thanks for your comments. You’re correct, as the current endpoint has worked for so long, perhaps it’s a Twitter issue. The change in this PR simply changes the endpoint without attempting to understand why the existing endpoint no longer works (I’m assuming it is depreciated). Perhaps the best approach is wait until the endpoint works again?

2021-04-24 15:52 UTC, mtrezza commented
This still doesn't make any sense to me. This PR changes to a completely different endpoint.

2021-04-24 22:40 UTC, mtrezza commented
After identifying the [underlying issue](https://github.com/parse-community/parse-server/issues/7369#issuecomment-826159851), I suggest the following changes:

- Use a different endpoint
  The suggested endpoint `/1.1/oauth/request_token` is not a valid endpoint according to the docs. It returns the expected invalid auth response but so does `/1.1/oauth/blabla`. Also, it is a documented as a POST endpoint, but the test is for a GET endpoint. It's surprising that the test passes, likely because the Twitter API is quite graceful. Also, the endpoint does not require auth, it is an endpoint to *authenticate*, not to request a resource that *requires authentication*, which is what the test is about.

- Use endpoint `/1.1/account/settings.json`
  It's the same endpoint the `POST` test uses below the `GET` test; the endpoint is actually a POST and GET endpoint, so we don't need to rely on two dummy endpoints.

- Add a comment to the test
  To avoid confusion in the future, we should add a line to both tests (POST and GET) that these endpoints are just picked as dummies to test auth failing, for example:
  > Note: This endpoint has been chosen to make a request to an endpoint that requires OAuth which failed due to missing authentication. Any other endpoint from the [Twitter API](https://developer.twitter.com/en/docs/api-reference-index) that requires OAuth can be used instead in case the currently used endpoint deprecates.

2021-04-24 22:41 UTC, mtrezza commented
After identifying the [underlying issue](https://github.com/parse-community/parse-server/issues/7369#issuecomment-826159851), I suggest the following changes:

- Use a different endpoint
  The suggested endpoint `/1.1/oauth/request_token` is not a valid endpoint according to the docs. It returns the expected invalid auth response but so does `/1.1/oauth/blabla`. Also, it is a documented as a POST endpoint, but the test is for a GET endpoint. It's surprising that the test passes, likely because the Twitter API is quite graceful. Also, the endpoint does not require auth, it is an endpoint to *authenticate*, not to request a resource that *requires authentication*, which is what the test is about.

- Use endpoint `/1.1/account/settings.json`
  It's the same endpoint the `POST` test uses below the `GET` test; the endpoint is actually a POST and GET endpoint, so we don't need to rely on two dummy endpoints.

- Add a comment to the test
  To avoid confusion in the future, we should add a line to both tests (POST and GET) that these endpoints are just picked as dummies to test auth failing, for example:
  > Note: This endpoint has been chosen to make a request to an endpoint that requires OAuth which failed due to missing authentication. Any other endpoint from the [Twitter API](https://developer.twitter.com/en/docs/api-reference-index) that requires OAuth can be used instead in case the currently used endpoint deprecates.

2021-04-25 02:52 UTC, dblythy commented
Thanks for the suggestions! I'll add the changes.

2021-04-25 07:56 UTC, mtrezza requested changes
Formally requesting the changes so we don't merge with invalid endpoint by mistake.

2021-04-25 07:56 UTC, mtrezza commented on spec/OAuth1.spec.js
> +    const path = '/1.1/oauth/request_token';
This endpoint is invalid, change to same as POST endpoint.

2021-04-25 07:56 UTC, mtrezza commented on spec/OAuth1.spec.js
> -    const path = '/1.1/help/configuration.json';
Add comment why this endpoint is used.

2021-04-25 07:56 UTC, mtrezza commented on spec/OAuth1.spec.js
>        consumer_secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
Change credentials to `invalid`.

2021-04-25 09:57 UTC, mtrezza requested changes

2021-04-25 09:57 UTC, mtrezza commented on spec/OAuth1.spec.js
> +  it('GET request should fail with invalid credentials', done => {
Looks already much better. Can you just add `for a resource that requires OAuth` to both tests? To explicitly describe the purpose of the test for future changes.

2021-04-25 12:40 UTC, mtrezza commented
This looks good! Any thing you want to add before merging?

2021-04-25 12:42 UTC, dblythy commented
Nope! I'm ready to merge 😊

2021-04-25 12:50 UTC, merged

2021-04-25 12:52 UTC, mtrezza reviewed
LGTM Thanks for tackling this so quickly!

2021-11-01 16:30 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

2022-03-14 13:02 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)