feat: add content length and type http headers  to webhook POST request
parse-community/parse-server pull request #7647
Opened 2021-10-19 04:10 UTC by aecorredor

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues/7646).

### Issue Description

See more details about the fix in https://github.com/parse-community/parse-server/issues/7646.

Related issue: https://github.com/parse-community/parse-server/issues/7646

### Approach

Improves `httpRequest` so that when it makes a JSON request, it also adds the `Content-Length` header so consumers can accurately parse the body. Ultimately, this is so that webhooks work correctly with platforms like Vercel, which were losing the body of the request because the `Content-Length` header was not present. I could have just added the header in the `HooksController`, but it seemed that doing it directly in the `httpRequest` was the better approach so that whenver we use `httpRequest` we get the expected header.

### TODOs before merging

None that I can think of.

- [x] Add test cases
- [ ] Add entry to changelog

2021-10-19 04:10 UTC, aecorredor commented on src/cloud-code/httpRequest.js
> +      headers['Content-Length'] = Buffer.byteLength(body);
Mutating the headers object directly didn't seem too bad here.

2021-10-19 07:18 UTC, mtrezza requested changes

2021-10-19 07:18 UTC, mtrezza commented on spec/HTTPRequest.spec.js
> +        'Content-Length': Buffer.byteLength(body),
Could you add the test assertions that the content length and type are set?

2021-10-19 13:50 UTC, aecorredor commented on spec/HTTPRequest.spec.js
> +        'Content-Length': Buffer.byteLength(body),
Oof, my bad, don't know how I missed that. Done.

2021-10-19 13:52 UTC, aecorredor commented on spec/HTTPRequest.spec.js
> +    expect(result.headers['Content-Length']).toEqual(13);
Jasmine didn't like when I used `Buffer.byteLength(body)` here, so I just hard coded the expected value.

2021-10-19 17:23 UTC, mtrezza commented on spec/HTTPRequest.spec.js
> +    expect(result.headers['Content-Length']).toEqual(13);
looks fine

2021-10-19 17:57 UTC, mtrezza commented
Should the tests rather go into `ParseHooks.spec.js` and the changes into `HookController.js`? If I read the code correctly, the POST request for hooks is composed in a wrapper:

https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/src/Controllers/HooksController.js#L187-L208

Or do I misunderstand the original issue?

2021-10-19 18:04 UTC, aecorredor commented
> Should the tests rather go into `ParseHooks.spec.js` and the changes into `HookController.js`? If I read the code correctly, the POST request for hooks is composed in a wrapper:
> 
> https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/src/Controllers/HooksController.js#L187-L208
> 
> Or do I misunderstand the original issue?

Yeap, so I think we could have gone the two ways as I pointed out in the `approach` paragraph. The hooks do wrap the request, and we could just have added the header there. But, it seems that the more correct approach was to just add it to the general `httpRequest` because any time we make a JSON POST request we should be adding the `Content-Length`.

That's how I saw it, let me know if that makes sense or if there is a reason why we would not want to add it to the `httpRequest` directly.

2021-10-20 22:53 UTC, mtrezza commented
> if there is a reason why we would not want to add it to the httpRequest directly

The `request` may be used for other purposes in the future, not just for hooks. Not all types of requests may want to transmit that header or calculate the header in a different way, see [http specs](https://httpwg.org/specs/rfc7230.html#rfc.section.3.3.2). However, the specs also say:

> Aside from the cases defined above, in the absence of Transfer-Encoding, an origin server SHOULD send a Content-Length header field when the payload body size is known prior to sending the complete header section.

So I guess we can put it into the request method for now. If future changes require to modify that header, they should take that into account.

2021-10-20 23:05 UTC, mtrezza commented
This is almost ready for merge, could you just add a change log entry?

2021-10-21 15:10 UTC, aecorredor commented
> This is almost ready for merge, could you just add a change log entry?

I was looking for some examples on how to correctly add the change log entry, but couldn't find anything in some of the latest PRs that have merged. From the contributing guide, it seems like it gets generated automatically depending on the conventional commit right? Is it just adding it to the unreleased section?

Anyway, if you could point me out to the correct format and where to add it, I'd appreciate it. Thanks.

2021-10-21 15:29 UTC, mtrezza commented
Change log entry still needs to be done manually in this repo; I reformatted the entry. I think it's good now.

2021-10-21 15:31 UTC, mtrezza approved these changes
Looks good! Thanks for this PR! Just waiting for the build to pass.

2021-10-21 16:00 UTC, aecorredor commented
@mtrezza anytime, thanks for taking the time to review + chime in on the Moralis forum.

Btw, checks got cancelled for some reason.

2021-10-23 13:45 UTC, mtrezza commented
Sure thing, thanks for improving Parse Server! Restarted the builds, let's see if they pass...

2021-10-29 01:53 UTC, mtrezza commented
@aecorredor could you please merge the `alpha` branch into this PR and resolve any conflicts? You can revert any changes in the changelog file, the entry will be made automatically.

2021-11-01 14:54 UTC, aecorredor commented
> @aecorredor could you please merge the `alpha` branch into this PR and resolve any conflicts? You can revert any changes in the changelog file, the entry will be made automatically.

Done. Let me know if it's all good now.

2021-11-01 21:21 UTC, mtrezza approved these changes
Looks good! CI seems to pass.

2021-11-01 22:47 UTC, mtrezza commented
Interestingly, the tests seem to fail consistently, I tried to re-run them several times. Do these tests pass locally for you?

2021-11-05 13:58 UTC, aecorredor commented
> Interestingly, the tests seem to fail consistently, I tried to re-run them several times. Do these tests pass locally for you?

Which tests specifically? Unit tests do pass for me. Not sure how the other ones are related to my change though. Do you think the content-length header might be affecting some stuff?

2021-11-05 15:55 UTC, mtrezza commented
>  Do you think the content-length header might be affecting some stuff?

Maybe, it seems to be related to Parse Cloud Job calls. You can see the failing tests here:
https://github.com/parse-community/parse-server/runs/4073196917?check_suite_focus=true

2021-11-19 21:23 UTC, aecorredor commented
Unfortunately, I don't currently have the bandwidth to dig more into the repo to find out what might have caused the test failures. Moralis did incorporate the fix into their fork, so I was unblocked. I'll close this for now and we can revisit it in the future if others start needing this at some point. Apologies for not having been able to get this all the way through.

2021-11-19 21:23 UTC, closed without merging