Do not require addField permissions unless the root field does not exist (Rebase of #7372)
parse-community/parse-server pull request #7679
Opened 2021-11-04 18:37 UTC by bdevore17

Also added a corresponding regression test

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description
This PR is the rebased version of #7372 

Related issue: #7372 and #7371 

### Approach
See #7371 

### TODOs before merging

- [x] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2021-11-04 23:47 UTC, mtrezza requested changes

2021-11-04 23:47 UTC, mtrezza commented on spec/schemas.spec.js
> +    it('addField not required for adding a nested field (#7371)', async () => {
could you please rename to:

> it('addField permission not required for adding a nested property', async () => {

2021-11-04 23:47 UTC, mtrezza commented on spec/schemas.spec.js
> +    it('addField not required for modifying a nested field (#7371)', async () => {
could you please rename to:

> it('addField permission not required for modifying a nested property', async () => {

2021-11-05 14:29 UTC, bdevore17 commented
@mtrezza done!. Let me know if you need anything else here.

2021-11-08 17:47 UTC, bdevore17 commented
brought this up to date with alpha^

2021-11-08 22:54 UTC, mtrezza approved these changes
Looks good! Thanks for the fix.

2021-11-15 16:12 UTC, bdevore17 commented
@mtrezza What do I need to do here? It doesn't seem like any of these failures relate to this PR.

2021-11-16 12:51 UTC, mtrezza commented
@bdevore17 could you just bring this branch up-to-date to see if the tests pass? We have merged some fixes on the alpha branch.

2021-11-16 17:55 UTC, bdevore17 commented
@mtrezza done!

2021-11-17 12:18 UTC, mtrezza commented
Restarted the CI, let's see whether it passes.

2021-11-30 13:34 UTC, bdevore17 commented
@mtrezza looks like it passed. Can this now be merged?

2021-12-06 14:15 UTC, mtrezza commented
Could you update the branch please?

2021-12-06 20:26 UTC, bdevore17 commented
@mtrezza done!

2021-12-06 23:53 UTC, merged

2021-12-06 23:54 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-alpha.12](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.12)

2022-03-15 00:18 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

2022-03-18 14:53 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)