fix: Pass context to afterFind hook while making object.fetch call.
parse-community/parse-server pull request #7779
Opened 2022-01-21 10:52 UTC by yog27ray

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

This extension the of the https://github.com/parse-community/parse-server/pull/6626. To pass context while making fetch call.

### TODOs before merging

- [x] Add tests

2022-01-21 13:56 UTC, mtrezza reviewed
It seems that this adds the context option to the `ParseObject.fetch` method in general, so it's not just related to `afterFind`, but it also works for `beforeFind`, correct?

2022-01-21 14:21 UTC, yog27ray commented
@mtrezza yes, the same context will be passed to beforeFind and then to afterFind also.

2022-01-21 20:00 UTC, mtrezza commented
Great, just wanted to make sure to name the PR title correctly for the changelog entry. Could you add `beforeFind` to the existing test?

2022-01-25 00:38 UTC, mtrezza requested changes

2022-01-25 00:38 UTC, mtrezza commented on spec/CloudCode.spec.js
> +  it('beforeFine and afterFind should have access to context while making fetch call', async () => {
typo `beforeFind`

2022-01-25 11:39 UTC, mtrezza approved these changes
Looks good!

2022-01-25 11:40 UTC, merged

2022-01-25 11:41 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-alpha.21](https://github.com/parse-community/parse-server/releases/tag/5.0.0-alpha.21)

2022-03-15 00:17 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.10](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.10)

2022-03-18 14:52 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-server/releases/tag/5.1.0)