feat: add definitions CI check
parse-community/parse-server pull request #7955
Opened 2022-04-28 05:17 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Often, the definitions files are manually edited.

Related issue: #7918

### Approach

Generates definitions and compares to committed definitions

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-04-28 13:38 UTC, dblythy commented
Not quite sure why this runs fine locally but github actions responds with `[Error: ENOENT: no such file or directory, open './src/options/Definitions.js'] {`

2022-04-28 15:09 UTC, mtrezza commented
Likely because in the GH container environment the path root is different from your local env.

2022-04-28 15:25 UTC, dblythy commented
Ok, thanks for the pointers CI expert! If you could have a quick look at the approach and let me know your general thoughts some time that would be great.

2022-04-28 15:49 UTC, mtrezza requested changes

2022-04-28 15:49 UTC, mtrezza commented on package.json
> +    "definitions:test": "node ./resources/checkDefinitions.js",
Could you rename this to `ci:checkDefinitions` and move it to that group?

2022-04-28 15:49 UTC, mtrezza commented on resources/checkDefinitions.js
> +const fs = require('fs').promises;
Could you move this file to the other CI check scripts in the `/ci` directory, and maybe rename it to `definitionsCheck.js`?

2022-04-28 15:49 UTC, mtrezza commented on resources/checkDefinitions.js
> +  await new Promise(resolve => setTimeout(resolve, 2000));
Instead of timeout, could you use 
```
const exec = util.promisify(require('child_process').exec);
await exec('npm run definitions');
```

2022-04-28 15:49 UTC, mtrezza commented on resources/checkDefinitions.js
> +  const [nowDefinitions, nowDocs] = await Promise.all([
Could you rename this to `new...` instead of `now...`? I think it sounds slightly more descriptive than a time reference.

2022-04-28 15:49 UTC, mtrezza commented on resources/checkDefinitions.js
> +})();
Could you use `const core = require('@actions/core');` and in addition to logging a `console.log` use `core.error`. See the existing checks in `/ci` directory. IIRC I've kept the `console.log` logging only for debug purposes because `core` logs are not displayed locally. That core lib is quite convenient, you can define for example what is displayed as the main error for the failing CI job in the CI summary.

2022-04-28 15:49 UTC, mtrezza commented on src/Options/Definitions.js
> +  manuallyEditedOption: true,
What's the purpose of this?

2022-04-28 15:54 UTC, dblythy commented on src/Options/Definitions.js
> +  manuallyEditedOption: true,
Sorry. That was just to make sure the test failed the CI. Once it’s ready and working this will be removed

2022-06-08 12:18 UTC, Moumouls commented on package.json
> +    "ci:definitionsCheck": "node ./ci/definitionsCheck.js",
i can suggest adding this line directly to `lint` command.
Parse repo has a git hook before committing. Then this check could help and fail earlier at commit time 👍

2022-06-08 12:18 UTC, Moumouls commented on package.json
> +    "ci:definitionsCheck": "node ./ci/definitionsCheck.js",
otherwise the strategy looks good to me 🙂

2022-12-17 02:25 UTC, mtrezza approved these changes
That's a very cool one! Will have us a quite some trouble in the future.

2022-12-17 12:13 UTC, mtrezza commented on package.json
> +    "ci:definitionsCheck": "node ./ci/definitionsCheck.js",
It has nothing to do with lint, so we won't do that.

2022-12-17 12:15 UTC, merged

2022-12-20 15:59 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.15](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.15)

2023-01-31 03:21 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

2023-01-31 03:40 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)