fix: push notifications `badge` doesn't update with Installation beforeSave trigger
parse-community/parse-server pull request #8162
Opened 2022-09-11 07:45 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

beforeSave triggers on the `Installation` class prevent `badge` being tracked.

Related issue: #8118

### Approach

If `this.runOptions.many`, do not run the triggers. `many` is used to run `updateMany`, which is used internally to update `badge` in pushes.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-09-14 12:22 UTC, mtrezza requested changes

2022-09-14 12:22 UTC, mtrezza commented on spec/ParseInstallation.spec.js
> +  it('can use  push with beforeSave', async () => {
```suggestion
  it('can use push with beforeSave', async () => {
```

2022-09-14 12:22 UTC, mtrezza commented on spec/ParseInstallation.spec.js
> +
```suggestion
```

2022-09-14 12:24 UTC, mtrezza approved these changes
Waiting for CI to pass, then ready for merge

2022-09-16 19:43 UTC, merged

2022-09-16 19:52 UTC, parseplatformorg commented
🎉 This change has been released in version [5.3.0-alpha.22](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.22)

2022-10-29 20:07 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

2022-10-31 14:44 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

2022-11-19 03:44 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

2022-11-19 11:49 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)