ci: update versions and remove EOL deps
parse-community/parse-server pull request #8191
Opened 2022-09-22 13:38 UTC by cbaker6

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

The CI isn't testing against the current latest versions of dependencies (e.g. Postgis 3.3) and still testing against dependencies that has reached the Parse EOL. This prevents the CI from determining if there are issues with the latest versions along with running unnecessary tests for each PR.

Related issue: n/a

### Approach

Update versions of Postgis, remove versions that have reached EOL: Postres 11, Postgis 3.0, Node 12, Mongo 4.0. 

### TODOs before merging

- [ ] Ensure CI passes
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-09-22 15:30 UTC, cbaker6 commented
@parse-community/server this is ready for review

2022-09-22 17:21 UTC, mtrezza commented
Removing support for a database or node major version is a breaking change, which we'll do with Parse Server 6.

Therefore we do have specific open issues for that, e.g. https://github.com/parse-community/parse-server/issues/8081.

So it makes more sense to separate this PR into:

- a) Removing support for versions that won't be supported anymore by Jan 1st 2023 according to their EOL date.
- b) Upgrading versions of currently supported versions

2022-09-22 17:29 UTC, mtrezza requested changes
See https://github.com/parse-community/parse-server/issues/8192#issuecomment-1255332240

2022-09-22 20:41 UTC, mtrezza commented
@cbaker6 I've renamed the PR to only do the version upgrade, I think you can remove changes that are removing support for versions. Then we can merge this PR as only upgrading existing versions.

2022-09-23 17:04 UTC, mtrezza approved these changes
Looks good!

2022-09-23 23:06 UTC, merged

2022-09-29 23:03 UTC, parseplatformorg commented
🎉 This change has been released in version [5.3.0-alpha.27](https://github.com/parse-community/parse-server/releases/tag/5.3.0-alpha.27)

2022-10-29 20:06 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-beta.1)

2022-10-31 14:43 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/5.4.0-alpha.1)

2022-11-19 03:43 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)

2022-11-19 11:48 UTC, parseplatformorg commented
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-server/releases/tag/5.4.0)