feat: Limit masterKey to localhost
parse-community/parse-server pull request #8281
Opened 2022-11-03 02:01 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Currently, there is no restriction to the Parse Server option `masterKeyIps`.

Related issue: #8245
Closes: #8245

### Approach

Changes the default `masterKeyIps` to `127.0.0.1`. Also allows CIDR ranges for `masterKeyIps`.

This is a breaking change as `masterKeyIps` set to `[]` will be "allow from no-where".

This also allows developers to set `0.0.0.0/0` as "allow from everywhere".

Also changes the default behaviour for if a valid masterKey is provided from an invalid IP. Allows the request to continue (whilst setting auth.master to false) as this provides security through obscurity.

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-11-03 09:05 UTC, Moumouls commented
we should flag this one as state breacking @mtrezza  ?

2022-11-10 16:42 UTC, mtrezza requested changes

2022-11-10 16:42 UTC, mtrezza commented on src/Options/index.js
>    /* Restrict masterKey to be used by only these ips, defaults to [] (allow all ips)
Could you add more instructions here, regarding optional CIDR notation, etc

2022-11-10 23:37 UTC, dblythy commented on src/Options/index.js
>    /* Restrict masterKey to be used by only these ips, defaults to [] (allow all ips)
How's that look?

2022-11-10 23:44 UTC, mtrezza commented
I think we were rewriting the definitions at the same time, sorry about that.

2022-11-10 23:45 UTC, mtrezza commented on src/Options/index.js
>    /* Restrict masterKey to be used by only these ips, defaults to [] (allow all ips)
I think we were rewriting the definitions at the same time, sorry about that.

2022-11-11 01:17 UTC, mtrezza commented on src/Config.js
>          throw `Invalid ip in masterKeyIps: ${ip}`;
```suggestion
        throw `Invalid IP address '${ip}' in option masterKeyIps`;
```

2022-11-11 01:21 UTC, mtrezza commented
Suggested changelog note:

> BREAKING CHANGE: This release restricts the use of `masterKey` to localhost by default; if you are using Parse Dashboard on a different server to connect to Parse Server you need to add the IP address of the server that hosts Parse Dashboard to this option, because Parse Dashboard uses the master key (#8281)

2022-11-11 02:24 UTC, merged

2022-11-11 02:27 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.8](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.8)

2023-01-31 03:22 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

2023-01-31 03:40 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)