fix: Replace existing HTTP request module
parse-community/parse-server pull request #8282
Opened 2022-11-03 03:29 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Currently, Parse Server uses a custom HTTP implementation to perform request for hooks, tests, as well as `Parse.Cloud.httpRequest`

Related issue: #8271, #7589
Closes: #8271, #7589

### Approach

Replaces existing module with axios.

### TODOs before merging

- [x] Add tests
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-11-03 03:32 UTC, dblythy commented
This also un-depreciates `Parse.Cloud.httpRequest`

2022-11-03 05:01 UTC, dblythy commented
Changes work for 99% of tests, however for some tests the new request method fails. I've added `request.legacy` to circumvent this.

2022-11-03 20:14 UTC, mtrezza requested changes
It would be better if we could have 1 PR per issue, because they are different in nature; one is an internal refactor and unrelated to Parse Server 6, the other is a breaking change. Could you
- create a new PR to remove the deprecation for https://github.com/parse-community/parse-server/issues/8271
- after merging rebase this PR to refactor internally https://github.com/parse-community/parse-server/issues/7589

2022-11-03 20:14 UTC, mtrezza commented on src/cloud-code/Parse.Cloud.js
> +import axios from 'axios';
Also here, shouldn't this be removed entirely?

2022-11-03 20:14 UTC, mtrezza commented on src/cloud-code/httpRequest.js
> +import axios from 'axios';
Shouldn't `Parse.Cloud.httpRequest` be removed entirely? We aren't offering this method anymore to developers. Or is used by Parse Server internally?

2022-11-03 20:14 UTC, mtrezza commented on DEPRECATIONS.md
> -| DEPPS4 | Remove convenience method for http request `Parse.Cloud.httpRequest` | [#7589](https://github.com/parse-community/parse-server/pull/7589)   | 5.0.0 (2022)                    | 6.0.0 (2023)
This line should stay, only the status should changed to "removed".

2022-11-03 23:43 UTC, dblythy commented
Here I am suggesting keeping `Parse.Cloud.httpRequest` as an alias to `axios`.

I'm not quiet sure how they are seperate issues - in order to remove the old method, we need to introduce a new one so that the tests can pass (as the tests extensively use the http module)

2022-11-03 23:59 UTC, mtrezza commented
Issue 1 is to remove the `Parse.Cloud.httpRequest` method as described in https://github.com/parse-community/parse-server/issues/8271. The method is deprecated, so it should not be available anymore in Cloud Code for developers to use.

Issue 2 is to replace the node http with axios, which only an internal refactor, once issue 1 is done, because it's not exposed through `Parse.Cloud.httpRequest` anymore.

You could forget about issue 2 for a second and imagine we don't want to switch to axios. Issue 1 would only remove the method `Parse.Cloud.httpRequest`.

2022-11-04 00:07 UTC, dblythy commented
If that is the case and we are not exposing it externally - is there any real purpose in replacing the HTTP module? Adding an extra dependency with the only production use of hooks, seems a bit extraneous. We could continue to use the HTTP module for tests (and perhaps refactor / update some of the depreciated methods) but remove `Parse.Cloud.httpRequest`

2022-11-04 00:16 UTC, mtrezza commented
> If that is the case and we are not exposing it externally - is there any real purpose in replacing the HTTP module?

I thought so because you [wrote](https://github.com/parse-community/parse-server/issues/7589#issue-1003845237):

> Why should we continue to support a legacy HTTP module, which hasn't been updated in 3 years, where there are more popular solutions that constantly update their security issues and vulnerabilities? The http module also uses deprecated methods, such as querystring and parse.

2022-11-04 00:25 UTC, mtrezza commented
I suggest to first remove the external method in a separate, and then modify this PR to replace the http lib. That may be easier than the other way around.

2022-11-04 00:32 UTC, dblythy commented
Ideally pretty much every test that uses `request` should be refactored

2022-11-04 01:26 UTC, dblythy commented
Closing as Node 18 will support native `fetch`, we will replace the internal http request module for tests with Parse Server 7.

2022-11-04 01:26 UTC, closed without merging

2022-11-04 01:38 UTC, mtrezza commented
More details in https://github.com/parse-community/parse-server/issues/7589#issuecomment-1302852075