fix: remove mongoDB 4.0
parse-community/parse-server pull request #8292
Opened 2022-11-06 04:55 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Removes support for mongodb 4.0

Related issue: #8272

### Approach

Removes support for mongodb 4.0

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-11-06 04:56 UTC, dblythy commented
I cannot find any tests that use `it_only_mongodb_version` for v4.0

2022-11-06 05:50 UTC, dblythy commented
Can this and #8273 be resolved in the same PR?

2022-11-06 12:51 UTC, mtrezza commented
Yes, I think so

2022-11-10 15:44 UTC, mtrezza requested changes
~~Could you remove the conflicts?~~

Done

2022-11-10 21:12 UTC, mtrezza commented on package.json
>      "test:mongodb:4.0.28": "npm run test:mongodb --dbversion=4.0.28",
```suggestion
```

2022-11-10 21:13 UTC, mtrezza approved these changes
Looks good!

2022-11-10 21:21 UTC, merged

2022-11-10 22:34 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.6](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.6)

2023-01-31 03:22 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

2023-01-31 03:41 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)