feat: remove custom aggregate syntax
parse-community/parse-server pull request #8362
Opened 2022-12-28 01:30 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

Parse Server previously used a custom aggregate syntax.

Closes: #8268

### Approach

Remove old syntax

### TODOs before merging

- [x] Add tests

2022-12-28 01:32 UTC, dblythy commented
Depends on a JS SDK release after the merge of https://github.com/parse-community/Parse-SDK-JS/pull/1642 in order for tests to pass

2022-12-28 12:11 UTC, mtrezza requested changes
Just some log rephrasing

2022-12-28 12:11 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +        'Pipeline stages should only have one key. Found $group, $match'
```suggestion
        'Pipeline stages should only have one key but found $group, $match.'
```

2022-12-28 12:11 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +        'Pipeline stages should only have one key. Found $group, $match'
```suggestion
        'Pipeline stages should only have one key but found $group, $match.'
```

2022-12-28 12:11 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +      new Parse.Error(Parse.Error.INVALID_QUERY, `Invalid aggregate stage: foo.`)
```suggestion
      new Parse.Error(Parse.Error.INVALID_QUERY, `Invalid aggregate stage 'foo'.`)
```

2022-12-28 12:11 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +      new Parse.Error(Parse.Error.INVALID_QUERY, `Cannot use objectId in aggregation stage $group.`)
```suggestion
      new Parse.Error(Parse.Error.INVALID_QUERY, `Cannot use 'objectId' in aggregation stage $group.`)
```

2022-12-28 12:11 UTC, mtrezza commented on src/Routers/AggregateRouter.js
> +          `Cannot use objectId in aggregation stage $group.`
```suggestion
          `Cannot use 'objectId' in aggregation stage $group.`
```

2022-12-28 12:11 UTC, mtrezza commented on src/Routers/AggregateRouter.js
> +          `Pipeline stages should only have one key. Found ${keys.join(', ')}`
```suggestion
          `Pipeline stages should only have one key but found '${keys.join('\', \'')}'`
```

2022-12-31 03:56 UTC, mtrezza commented
Seems there's still some adjustment necessary after the commits, could you take a look?

2023-01-05 00:00 UTC, mtrezza requested changes
Punctuation added to error messages.

2023-01-05 00:00 UTC, mtrezza commented on src/Routers/AggregateRouter.js
> +          `Pipeline stages should only have one key but found ${keys.join(', ')}`
```suggestion
          `Pipeline stages should only have one key but found ${keys.join(', ')}.`
```

2023-01-05 00:00 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +      new Parse.Error(Parse.Error.INVALID_QUERY, `Invalid aggregate stage: foo.`)
```suggestion
      new Parse.Error(Parse.Error.INVALID_QUERY, `Invalid aggregate stage 'foo'.`)
```

2023-01-05 00:00 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +        'Pipeline stages should only have one key but found $group, $match'
```suggestion
        'Pipeline stages should only have one key but found $group, $match.'
```

2023-01-05 00:00 UTC, mtrezza commented on spec/AggregateRouter.spec.js
> +        'Pipeline stages should only have one key but found $group, $match'
```suggestion
        'Pipeline stages should only have one key but found $group, $match.'
```

2023-01-05 00:01 UTC, mtrezza commented on src/Routers/AggregateRouter.js
> +      throw new Parse.Error(Parse.Error.INVALID_QUERY, `Invalid aggregate stage: ${stageName}.`);
```suggestion
      throw new Parse.Error(Parse.Error.INVALID_QUERY, `Invalid aggregate stage '${stageName}'.`);
```

2023-01-05 14:26 UTC, mtrezza approved these changes, later dismissed

2023-01-05 14:53 UTC, merged

2023-01-05 14:55 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.19)

2023-01-31 03:21 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

2023-01-31 03:39 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)