feat: re-add schema pulling
parse-community/parse-server pull request #8436
Opened 2023-02-22 07:37 UTC by dblythy

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

If a developer is not using `enableSchemaHooks`, the server will have to be restarted to fetch new schema data

Closes: #8229

## Approach

Adds a conditional reload of schema if it hasn't been refreshed below `databaseOptions.schemaCacheTTL`

## Tasks

- [x] Add tests

2023-02-22 07:41 UTC, mtrezza commented
I think it would be good to make this TTL refresh optional. So if the option is not set, there should be no refresh happening, which is the status quote.

2023-02-25 18:44 UTC, mtrezza requested changes
What happens if `schemaCacheTtl` and `enableSchemaHooks` are set? Should both be enabled? There may be a use case for it, who knows. Or should it throw an error or a warning?

2023-02-25 18:44 UTC, mtrezza commented on src/Adapters/Storage/Mongo/MongoStorageAdapter.js
> +  schemaCacheTTL: ?number;
Use camel case `schemaCacheTtl`.

2023-02-25 23:35 UTC, dblythy commented
I think if they are both enabled:

- Schema will update when change event is triggered
- Schema will also pull every `ttl`

Perhaps if the network connection between the Parse Server and the database is inconsistent, `change` events might be missed.

2023-02-26 12:30 UTC, mtrezza commented
Makes sense, so let's just allow both features to be configures independently without any warning

2023-02-26 12:52 UTC, mtrezza requested changes
Adding doc

2023-02-26 12:52 UTC, mtrezza commented on src/Options/index.js
> +  /* The TTL for caching the schema for optimizing read/write operations. You should put a long TTL when your DB is in production */
```suggestion
  /* The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A low duration will cause the schema cache to be updated too often, causing unnecessary database reads. A high duration will cause the schema to be updated too rarely, increasing the time required until schema changes propagate to all server instances. This feature can be used as an alternative or in conjunction with the option `enableSchemaHooks`. By default this option is disabled and the schema cache never expires. */
```

2023-02-26 12:52 UTC, mtrezza commented on src/Options/docs.js
> + * @property {Number} schemaCacheTtl The TTL for caching the schema for optimizing read/write operations. You should put a long TTL when your DB is in production
```suggestion
 * @property {Number} schemaCacheTtl The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A low duration will cause the schema cache to be updated too often, causing unnecessary database reads. A high duration will cause the schema to be updated too rarely, increasing the time required until schema changes propagate to all server instances. This feature can be used as an alternative or in conjunction with the option `enableSchemaHooks`. By default this option is disabled and the schema cache never expires.
```

2023-02-26 12:52 UTC, mtrezza commented on src/Options/Definitions.js
> +      'The TTL for caching the schema for optimizing read/write operations. You should put a long TTL when your DB is in production',
```suggestion
      'The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A low duration will cause the schema cache to be updated too often, causing unnecessary database reads. A high duration will cause the schema to be updated too rarely, increasing the time required until schema changes propagate to all server instances. This feature can be used as an alternative or in conjunction with the option `enableSchemaHooks`. By default this option is disabled and the schema cache never expires.',
```

2023-02-26 12:54 UTC, mtrezza approved these changes, later dismissed
Looks good, waiting for CI...

2023-02-26 12:57 UTC, mtrezza reviewed
Doc rewording

2023-02-26 12:57 UTC, mtrezza commented on src/Options/index.js
> +  /* The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A
```suggestion
  /* The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A low duration will cause the schema cache to be updated too often, causing unnecessary database reads. A high duration will cause the schema to be updated too rarely, increasing the time required until schema changes propagate to all server instances. This feature can be used as an alternative or in conjunction with the option `enableSchemaHooks`. Default is infinite which means the schema cache never expires. */
```

2023-02-26 12:57 UTC, mtrezza commented on src/Options/docs.js
> + * @property {Number} schemaCacheTtl The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances co
```suggestion
 * @property {Number} schemaCacheTtl The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A low duration will cause the schema cache to be updated too often, causing unnecessary database reads. A high duration will cause the schema to be updated too rarely, increasing the time required until schema changes propagate to all server instances. This feature can be used as an alternative or in conjunction with the option `enableSchemaHooks`. Default is infinite which means the schema cache never expires.
```

2023-02-26 12:57 UTC, mtrezza commented on src/Options/Definitions.js
> +      'The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database.
```suggestion
      'The duration in seconds after which the schema cache expires and will be refetched from the database. Use this option if using multiple Parse Servers instances connected to the same database. A low duration will cause the schema cache to be updated too often, causing unnecessary database reads. A high duration will cause the schema to be updated too rarely, increasing the time required until schema changes propagate to all server instances. This feature can be used as an alternative or in conjunction with the option `enableSchemaHooks`. Default is infinite which means the schema cache never expires.',
```

2023-02-26 12:58 UTC, mtrezza approved these changes

2023-02-27 00:55 UTC, merged

2023-02-27 00:57 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.35](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.35)

2023-03-02 10:54 UTC, parseplatformorg commented
🎉 This change has been released in version [6.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.1)

2023-03-03 16:53 UTC, parseplatformorg commented
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

2023-05-01 21:52 UTC, parseplatformorg commented
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)