fix: reject signup with preventLoginWithUnverifiedEmail
parse-community/parse-server pull request #8451
Opened 2023-03-02 02:41 UTC by dblythy

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Current, when using `preventLoginWithUnverifiedEmail`, the save response is a 201, and the JS SDK assigns `Parse.User.current()` with an objectId, but no session token. Instead, the same response should return as a login, which is:

`new Parse.Error(Parse.Error.EMAIL_NOT_FOUND, 'User email is not verified.')`

Closes: #2863

## Approach

All other operations should occur, just the response should throw. There will need to be some refactoring, as currently the feature is implemented as:

```js
await user.signup();
await user.logout();
// we've sent you an email, please verify your email to continue
```

New:

```js
try {
  await user.signup();
} catch (e) {
  if (e.code === Parse.Error.EMAIL_NOT_FOUND) {
     // we've sent you an email, please verify your email to continue
  }
}
```

Perhaps we could add an option to the JS SDK signup method such as `{login: false}` that can determine whether signup can throw `User email is not verified`

## Tasks

- [x] Add tests

2023-03-06 13:02 UTC, mtrezza commented
Currently the response is 201 success and with the PR the response will be a 400 error? Isn't that a breaking change?

2023-03-06 23:29 UTC, dblythy commented
Is it considered a breaking change if it's a bug?

2023-03-07 00:18 UTC, mtrezza commented
There's no fixed rule. Generally, if it's incorrect behavior but not a security issue then we can assume developers found a workaround. Breaking that workaround would make it a breaking change, even if it's just correcting the incorrect behavior. If there is no practical workaround then it's not a breaking change. If the bug exists only in an alpha or beta pre-release then it's also not a breaking change, because we can fix that before official release.

2023-03-07 00:58 UTC, dblythy commented
It is a breaking change, so should we wait for a major release? How do you think we should approach this? 

If we leave it as a status 200, but return a response with no session token, the client SDKs will think the login was successful, assign a `Parse.User` with no session token, and future requests will fail with `cannot modify user`. 

```js
 const user = new Parse.User();
user.setPassword('asdf');
user.setUsername('zxcv');
user.set('email', 'testInvalidConfig@example.com');
await user.signUp(null);
console.log(Parse.User.current()) // is defined
user.set('foo', 'bar');
await user.save(); // cannot modify user
```

The current work around is:

```js
 const user = new Parse.User();
user.setPassword('asdf');
user.setUsername('zxcv');
user.set('email', 'testInvalidConfig@example.com');
await user.signUp(null);
await Parse.User.logOut()
```

2023-03-07 15:25 UTC, mtrezza commented
If we say this is breaking then we can
- leave as it until next major release
- add a server option with a deprecation that can released immediately as feature release

2023-03-29 00:33 UTC, dblythy commented
Refactored this to be a Parse Server option: `preventSignupWithUnverifiedEmail`

2023-05-18 01:11 UTC, mtrezza requested changes
I've added some more details to the option docs. Could you check whether I got this right and rebuild the definitions?

2023-05-18 01:11 UTC, mtrezza commented on src/Options/index.js
> +  preventSignupWithUnverifiedEmail: ?boolean;
```suggestion
  /* If set to `true` it prevents a user from signing up if the email has not yet been verified and email verification is required. In that case the server responds to the sign-up with HTTP status 400 and a Parse Error 205 `EMAIL_NOT_FOUND`. If set to `false` the server responds with HTTP status 200, and client SDKs return an unauthenticated Parse User without session token. In that case subsequent requests fail until the user's email address is verified.
  <br><br>
  Default is `false`.
  <br>
  Requires option `verifyUserEmails: true`.
  :DEFAULT: false */
  preventSignupWithUnverifiedEmail: ?boolean;
```

2023-05-18 01:16 UTC, mtrezza commented
The new PR title is somewhat long, but I thought "prevent sign-up with unverified email" sounds strange because an email address is always unverified on sign-up.

2023-06-07 14:12 UTC, dblythy commented
Sounds good to me!

2023-06-07 14:43 UTC, mtrezza approved these changes
Looks good, is this ready for merge?

2023-06-07 14:52 UTC, dblythy commented
Yep!

2023-06-07 19:51 UTC, merged

2023-06-07 19:53 UTC, parseplatformorg commented
🎉 This change has been released in version [6.1.0-alpha.17](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.17)

2023-06-10 23:07 UTC, parseplatformorg commented
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

2023-06-18 01:23 UTC, parseplatformorg commented
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

2023-09-16 01:11 UTC, parseplatformorg commented
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)