feat: add `security.enableCheck` status to FeaturesRouter
parse-community/parse-server pull request #8679
Opened 2023-06-30 03:50 UTC by dblythy

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Currently, the status of `security.enableCheck` is not passed to `FeaturesRouter`

Closes: #8678

## Approach

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

2023-07-03 00:07 UTC, mtrezza commented on src/Routers/FeaturesRouter.js
> +          security: !!config.security?.enableCheck,
Should this property be only called `security` or something more specific?

2024-03-23 23:23 UTC, mtrezza requested changes

2024-03-23 23:23 UTC, mtrezza commented on src/Routers/FeaturesRouter.js
> +          security: !!config.security?.enableCheck,
```suggestion
          securityCheck: !!config.security?.enableCheck,
```

2024-03-23 23:23 UTC, mtrezza commented on spec/SecurityCheck.spec.js
> +      expect(response.data.features.settings.security).toBeFalse();
```suggestion
      expect(response.data.features.settings.securityCheck).toBeFalse();
```

2024-03-23 23:23 UTC, mtrezza commented on spec/SecurityCheck.spec.js
> +      expect(response.data.features.settings.security).toBeTrue();
```suggestion
      expect(response.data.features.settings.securityCheck).toBeTrue();
```

2024-03-23 23:23 UTC, mtrezza approved these changes

2024-03-24 00:50 UTC, merged

2024-03-24 00:51 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-alpha.2](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.2)

2024-06-30 02:04 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

2024-06-30 02:25 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)