fix: default fileExtension regex does not allow text-plain
parse-community/parse-server pull request #8699
Opened 2023-07-23 14:31 UTC by dblythy

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8698

## Approach

Changes the default fileExtension regex

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

2023-07-28 21:44 UTC, mtrezza requested changes

2023-07-28 21:44 UTC, mtrezza commented on src/Options/Definitions.js
> +      "Sets the allowed file extensions for uploading files. The extension is defined as an array of file extensions, or a regex pattern.<br><br>It is recommended to restrict the file upload extensio
```suggestion
      "Sets the allowed file extensions for uploading files. The extension is defined as an array of file extensions, or a regex pattern.<br><br>It is recommended to restrict the file upload extensions as much as possible. HTML files are especially problematic as they may be used by an attacker who uploads a HTML form to look legitimate under your app's domain name, or to compromise the session token of another user via accessing the browser's local storage.<br><br>Defaults to `^(?!(h|H)(t|T)(m|M)(l|L)?$)` which allows any file extension except HTM(L) files.",
```

2024-03-10 14:01 UTC, mtrezza commented on src/Options/Definitions.js
> +      "Sets the allowed file extensions for uploading files. The extension is defined as an array of file extensions, or a regex pattern.<br><br>It is recommended to restrict the file upload extensio
fixed

2024-03-10 14:04 UTC, mtrezza commented
This PR should fix errors in https://github.com/parse-community/Parse-SDK-JS/pull/2089

2024-03-10 14:11 UTC, merged

2024-03-10 14:13 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-alpha.26](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.26)

2024-03-19 18:30 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

2024-03-19 20:46 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)