Fixed Redis 4 Reconnect Issue
parse-community/parse-server pull request #8706
Opened 2023-08-01 16:44 UTC by Vortec4800

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8705

## Approach

Adds mostly empty event handlers to the Redis client, which is now required for Redis 4.

## Tasks

- [X] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)

2023-08-03 06:39 UTC, mtrezza requested changes
Could you add a test that demonstrates the issue before adding the fix and the passes with the fix?

It seems strange that adding empty handlers fixed this. Could you add a Redis docs reference that describes this requirement?

This makes me think which version of Redis we are actually testing with. It seems we need a compatibility table to the README and test with multiple versions just like we do with MongoDB.

2023-08-03 13:10 UTC, Vortec4800 commented
I agree it's strange. Here is the Redis issue that led me to the solution for reference.

https://github.com/redis/node-redis/issues/2032

There's also some discussion on how to reliably recreate the issue, it seems that hosted Redis servers like Digital Ocean or Heroku do this pretty often. I don't think the server version matters for this, only the client version, and it seems these handlers didn't change between version 3.x of the client and 4.x - only their requirement to exist.

I'm not sure offhand how to test this scenario, but let me investigate and see if there's something I can put together for that.

2023-08-10 15:35 UTC, ChrisGrant commented
For what it is worth, I am seeing the same issue on Heroku with the latest version of parse-server (6.2.1).

Redis version is 6.2.13.

2023-08-15 21:29 UTC, mtrezza commented
@Vortec4800 Did you find a way to add a test for this? If not, we may as well merge as is.

2023-08-20 17:29 UTC, Vortec4800 commented
I'm sorry - work got busy and I haven't had a chance to look at this further. I did just add a quick change that should address the lint error, and log client errors via the internal logger. Take a look and let me know if that's appropriate. I can also add info logs to the other client events if you think that would be a good idea.

2023-08-21 17:43 UTC, mtrezza commented
Thanks for the commits, let's see if the CI passes...

2023-08-29 23:02 UTC, mtrezza commented
It's strange that this one Postgres job keeps failing in the CI, I've restarted it several times. Restarted again.

2023-08-30 00:52 UTC, merged

2023-08-30 00:53 UTC, parseplatformorg commented
🎉 This change has been released in version [6.3.0-alpha.8](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.8)

2023-09-16 02:54 UTC, parseplatformorg commented
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

2023-09-20 08:50 UTC, parseplatformorg commented
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

2023-11-16 15:28 UTC, parseplatformorg commented
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)