pass config object to parseObject function
parse-community/parse-server pull request #8784
Opened 2023-10-22 11:47 UTC by zivchen

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

https://github.com/parse-community/parse-server/issues/8783

Closes: FILL_THIS_OUT

## Approach

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

2023-10-22 17:00 UTC, mtrezza commented
Could you please add a test that demonstrates the server crash?

2023-10-23 01:22 UTC, sadortun approved these changes

2023-10-23 01:37 UTC, sadortun commented
@mtrezza I'm probably 100% looking at the wrong place, but where are the tests for `parseObject()` ?

2023-10-23 08:58 UTC, mtrezza commented
Did you look at the blame line to see whether there were test in the PR?

2023-12-09 20:49 UTC, sadortun commented
> Did you look at the blame line to see whether there were test in the PR?

Yes, and i don't really see test-cases covering the `parseObject()`   in your original commit where the original change were made. But i might be looking at the wrong place, or ` parseObject()` is tested indirectly.

https://github.com/parse-community/parse-server/commit/e212eb51954bfb5c49a59689fd785740489712fc#diff-8f2f0b3d469b333004223792d072d82895edc96039eae3dba67a4eb4e37ae66dR12

The missing test could simply add `[]`  to test  the `.map()`

Ex:  ` parseObject( [item]  , config);`

2023-12-11 19:39 UTC, rdhelms commented
Would love to see this fixed - we just tried to update and ran into this error

2023-12-11 22:29 UTC, pocketcolin commented
@sadortun I'm not a Parse maintainer but I think I figured out where this test should live and created a PR to the forked repo to add one that verifies this fix: https://github.com/zivchen/parse-server/pull/2

2023-12-11 22:38 UTC, pocketcolin commented
I just realized that the original creator of this PR hasn't replied since October 22 so I decided to go ahead and create a new PR with the test and fix so we can get it merged sooner. If the original creator comes back and wants to use their PR instead, that's also totally fine!

https://github.com/parse-community/parse-server/pull/8832

2023-12-12 06:59 UTC, zivchen commented
Hi
I merged @pocketcolin test spec into the PR
Thanks

2023-12-12 13:12 UTC, pocketcolin commented
Awesome! Should we also create a PR for a v6 hotfix? This PR just fixes the issue in the v7 alpha and who knows when v7 will be ready for prod.

2023-12-13 01:28 UTC, mtrezza commented
@zivchen Could you please edit the PR title so that it makes a meaningful change log entry where developers understand what issue this fixes?

2023-12-13 08:21 UTC, mtrezza commented
Could you rephrase the PR title so that it's less describing the source code and more the use case which causes the crash? It seems this only happens when using a Pointer, right?

2023-12-13 12:57 UTC, gtzinos commented
Just dropping a line to say we're eagerly eyeing this pull request, like kids at a candy store window. 😊

2023-12-14 08:11 UTC, vasileios-s approved these changes

2023-12-14 08:14 UTC, JohnStamtsidis approved these changes

2023-12-14 08:17 UTC, vaskouk approved these changes

2023-12-14 12:14 UTC, mtrezza requested changes

2023-12-14 12:14 UTC, mtrezza commented on spec/ParseAPI.spec.js
> +    }).then(response => {
Please rewrite using await; we are avoiding promise chains.

2023-12-14 12:14 UTC, mtrezza commented on spec/ParseAPI.spec.js
> +      url: 'http://localhost:8378/1/functions/echoParams', //?option=1&other=2
What is this query comment for, can it be removed?

2023-12-14 12:14 UTC, mtrezza commented on spec/ParseAPI.spec.js
> +      expect(res.foo).toEqual('bar');
Is this necessary, given that the query string is commented out? It looks like you were testing something additional (query para overwrite body param) that is beyond the test's purpose.

2023-12-14 12:19 UTC, mtrezza requested changes

2023-12-14 12:19 UTC, mtrezza commented on spec/ParseAPI.spec.js
> +      body: '{"foo":"bar", "other": 1, "arr": [{ "__type": "Pointer" }]}',
Is this actually a valid pointer object? It seems to be missing the classname and objectId?

Do we need `foo: bar` and `other: 1` in this test?

2023-12-14 12:28 UTC, mtrezza commented
We'll move Parse Server 6 to a LTS branch so a PR can be opened for it as well.

2024-01-14 23:40 UTC, mtrezza commented
@zivchen Just a friendly ping regarding the feedback; it would be great to get this PR merged.

2024-01-15 14:31 UTC, mtrezza commented on spec/ParseAPI.spec.js
> +  });
```suggestion
  it('test cloud function query parameters with array of pointers', async () => {
    Parse.Cloud.define('echoParams', req => {
      return req.params;
    });
    const headers = {
      'Content-Type': 'application/json',
      'X-Parse-Application-Id': 'test',
      'X-Parse-Javascript-Key': 'test',
    };
    const response = await request({
      method: 'POST',
      headers: headers,
      url: 'http://localhost:8378/1/functions/echoParams',
      body: '{"arr": [{ "__type": "Pointer", "className": "PointerTest" }]}',
    });
    const res = response.data.result;
    expect(res.arr.length).toEqual(1);
  });
```

2024-01-15 14:31 UTC, mtrezza commented on spec/ParseAPI.spec.js
> +  });
remove `done`, we're not using this anymore

2024-01-15 14:49 UTC, mtrezza approved these changes
Looks good, waiting for CI to pass...

2024-01-15 15:02 UTC, merged

2024-01-15 15:04 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.9)

2024-03-14 01:22 UTC, jaysonng commented
> Awesome! Should we also create a PR for a v6 hotfix? This PR just fixes the issue in the v7 alpha and who knows when v7 will be ready for prod.

yes pls. I need it for v6 and for the life of me can't figure out the proper procedure to do a PR for v6

2024-03-14 09:10 UTC, szymon-wrobel-pronos commented
@mtrezza Is there a timeline for carrying over this bugfix to the v6 version?

2024-03-19 18:32 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

2024-03-19 20:49 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)