feat: Add `silent` log level for Cloud Code
parse-community/parse-server pull request #8803
Opened 2023-11-10 02:18 UTC by dplewis

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Currently logs use `JSON.stringify` even if they aren't displayed to the console. `JSON.stringify` is one of the most CPU-intensive and this will improve performance. If you return a large amount of data from a cloud code function `JSON.stringify` will return `Invalid string length` error message.

Closes: https://github.com/parse-community/parse-server/issues/8418

## Approach

Add `silent` to `logLevels` Parse Server Config

```
{
  ...
  logLevels: {
    cloudFunctionSuccess: 'silent',
    cloudFunctionError: 'silent',
    triggerAfter: 'silent',
    triggerBeforeError: 'silent',
    triggerBeforeSuccess: 'silent',
  },
}
```
## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [x] Add new Parse Error codes to Parse JS SDK

2023-11-11 14:31 UTC, mtrezza requested changes

2023-11-11 14:31 UTC, mtrezza commented on spec/helper.js
> +    else return func;
```suggestion
    return func || it;
```

2024-03-21 15:19 UTC, mtrezza approved these changes

2024-03-21 15:19 UTC, merged

2024-03-21 15:20 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-alpha.31](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.31)

2024-03-23 00:53 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.1)

2024-06-30 02:05 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

2024-06-30 02:25 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)