refactor: Deprecated fields options removed
parse-community/parse-server pull request #8852
Opened 2023-12-28 08:35 UTC by onurhanife

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8845 

## Approach
In LiveQuery shema, deprecated fields otions removed

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

2023-12-30 08:00 UTC, mtrezza requested changes

2023-12-30 08:00 UTC, mtrezza commented on spec/ParseLiveQueryServer.spec.js
> +  xit('can deprecate fields', async () => {
Remove test if not needed anymore

2024-01-14 23:46 UTC, mtrezza approved these changes
Looks good

2024-02-14 23:30 UTC, mtrezza approved these changes

2024-02-14 23:31 UTC, merged

2024-02-14 23:32 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-alpha.16](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.16)

2024-03-19 18:32 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

2024-03-19 20:49 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)