Add databaseAdapter support for tests, REDACT databaseAdapter info wh…
parse-community/parse-server pull request #8883
Opened 2024-01-10 18:31 UTC by ddrechse

…en logging

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: FILL_THIS_OUT

## Approach

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK

2024-01-14 00:32 UTC, mtrezza requested changes

2024-01-14 00:32 UTC, mtrezza commented on spec/helper.js
> +    else return func;
```suggestion
    return func === undefined ? it : func;
```

2024-01-17 15:48 UTC, ddrechse commented on spec/helper.js
> +    else return func;
Merged

2024-01-19 12:25 UTC, mtrezza commented
@ddrechse Do you have an example that shows that this works?

2024-01-19 14:24 UTC, ddrechse commented
I do
I have added the adapter support to the repo here
https://github.com/oracle-samples/oracleadapter-parse

This is an example config.json for the Oracle Storage Adapter running against Free23c locally
```
{
  "appId": "APPLICATION_ID",
  "masterKey": "MASTER_KEY",
  "port": 1338,
  "logLevel": "info",
  "verbose": false,
  "mountGraphQL": true,
  "mountPlayground": true,
  "graphQLPath": "/graphql",
  "filesAdapter": {
    "module": "@parse/fs-files-adapter"
  },
  "databaseAdapter": {
    "module": "../Adapters/Storage/Oracle/OracleStorageAdapter",
    "options": {
      "databaseURI": "oracledb://pdbadmin:Welcome12345@localhost:1521/freepdb1",
      "collectionPrefix": ""
    }
  }
}  

```
@mtrezza

2024-01-19 19:04 UTC, mtrezza commented
Could you test this out by using the PR branch in https://github.com/parse-community/parse-server-database-adapter-template/pull/4?

2024-01-19 20:00 UTC, ddrechse commented
Yes it does

2024-04-05 23:17 UTC, dplewis commented
@mtrezza @ddrechse is this ready to merge? I have a MySQL adapter that can use this.

2024-04-05 23:41 UTC, mtrezza commented
@dplewis this is still ongoing development, partly outside of this org.

2024-04-26 23:20 UTC, mtrezza requested changes
Could you please check the coverage? Not sure if it's possible to write a simple test for this, otherwise we merge as is.

2024-05-14 22:07 UTC, mtrezza approved these changes, later dismissed
Looks good; waiting for CI to pass...

2024-05-14 22:15 UTC, mtrezza commented on src/cli/utils/runner.js
> +  const keysToRedact = ['databaseAdapter', 'databaseURI', 'masterKey', 'maintenanceKey', 'push'];
```suggestion
  const keysToRedact = [
    'databaseAdapter',
    'databaseURI',
    'masterKey',
    'maintenanceKey',
    'push',
  ];
```

2024-05-14 22:16 UTC, mtrezza approved these changes

2024-05-14 22:48 UTC, merged

2024-05-16 11:55 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-alpha.7](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.7)

2024-06-30 02:03 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

2024-06-30 02:24 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)