fix: `Required` option not handled correctly for special fields (File, GeoPoint, Polygon) on GraphQL API mutations
parse-community/parse-server pull request #8915
Opened 2024-02-07 14:19 UTC by Moumouls

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Closes: #8914

## Approach

Base all field detection on schema data ,and not on the GQL type ( like the Relation and Pointer type)

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [x] Add new Parse Error codes to Parse JS SDK

2024-02-10 15:47 UTC, mtrezza commented
Is this a breaking change?

2024-02-15 12:57 UTC, mtrezza commented
@Moumouls Could you please resolve the conflicts, and clarify whether this is a breaking change intended for Parse Server 7?

2024-03-17 23:29 UTC, mtrezza commented on spec/ParseGraphQLServer.spec.js
> +        log: () => { },
Could you remove these spaces inside the brackets? Seems to be added by your local lint?

2024-03-19 21:49 UTC, mtrezza requested changes
Requires lint fixes; it seems that the local lint adds spaces in curly braces and changes indentation.

2024-03-20 22:02 UTC, mtrezza approved these changes

2024-03-20 22:02 UTC, mtrezza commented on spec/ParseGraphQLServer.spec.js
> +        log: () => { },
fixed lint errors

2024-03-20 22:32 UTC, merged

2024-03-20 22:34 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-alpha.30](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.30)

2024-03-23 00:53 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.1)

2024-06-30 02:05 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

2024-06-30 02:25 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)