feat: dry handleAuthData for safer code maintenance in the futur
parse-community/parse-server pull request #9025
Opened 2024-03-17 19:08 UTC by Moumouls

## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Duplicated code related to an old GHSA on auth system. A quick dry refactor.

Closes: NONE

## Approach

A small DRY refactor for easiest, safer futur code maintenance on auth.

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)
- [x] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [x] Add new Parse Error codes to Parse JS SDK

2024-03-17 19:14 UTC, mtrezza requested changes

2024-03-17 19:14 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
Could you revert these? We usually have no space between empty curly brackets, but I think we are missing a lint rule for this

2024-03-19 21:28 UTC, mtrezza requested changes

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
```suggestion
      sendVerificationEmail: () => {},
```

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
```suggestion
      sendVerificationEmail: () => {},
```

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
```suggestion
      sendVerificationEmail: () => {},
```

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
```suggestion
      sendVerificationEmail: () => {},
```

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
```suggestion
      sendVerificationEmail: () => {},
```

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
```suggestion
      sendVerificationEmail: () => {},
```

2024-03-19 21:28 UTC, mtrezza commented on src/RestWrite.js
> +
```suggestion
```

2024-03-19 21:28 UTC, mtrezza commented on src/RestWrite.js
> +            'matches multiple Installation objects'
```suggestion
              'matches multiple Installation objects'
```

2024-03-19 21:28 UTC, mtrezza commented on spec/ParseUser.spec.js
> +          'Your account is locked due to multiple failed login attempts. Please try again after 1 minute(s)'
```suggestion
            e.message ===
              'Your account is locked due to multiple failed login attempts. Please try again after 1 minute(s)'
```

2024-03-19 21:31 UTC, mtrezza requested changes

2024-03-19 21:31 UTC, mtrezza commented on spec/AuthenticationAdaptersV2.spec.js
> +    spyOn(logger, 'error').and.callFake(() => { });
```suggestion
    spyOn(logger, 'error').and.callFake(() => {});
```

2024-03-19 21:31 UTC, mtrezza commented on spec/AuthenticationAdaptersV2.spec.js
> +    spyOn(logger, 'error').and.callFake(() => { });
```suggestion
    spyOn(logger, 'error').and.callFake(() => {});
```

2024-03-19 21:31 UTC, mtrezza commented on spec/AuthenticationAdaptersV2.spec.js
> +    spyOn(logger, 'error').and.callFake(() => { });
```suggestion
    spyOn(logger, 'error').and.callFake(() => {});
```

2024-03-19 21:41 UTC, mtrezza commented on spec/ParseUser.spec.js
> +      sendVerificationEmail: () => { },
Did some investigation and it seems there is currently no lint rule to control this; so we won't bother neither.

2024-03-19 21:41 UTC, merged

2024-03-20 22:34 UTC, parseplatformorg commented
🎉 This change has been released in version [7.0.0-alpha.30](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.30)

2024-03-23 00:53 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.1)

2024-06-30 02:05 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

2024-06-30 02:25 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)