fix: ExtendSessionOnUse Updates
parse-community/parse-server pull request #9113
Opened 2024-05-01 04:51 UTC by vivekjoshi556

## Pull Request
This PR helps with dynamically extending session based on session Length.

## Issue

Closes: #8981 

## Approach
I followed a similar approach to what @mman suggested [here](https://github.com/parse-community/parse-server/issues/8981#issuecomment-1976147677).

## Tasks
- [x] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

2024-05-01 04:54 UTC, vivekjoshi556 commented
Hello @mman,
You mentioned that you would beta test. Please look at the solution and let me know what you think.

2024-05-01 09:38 UTC, mman commented
Thanks a lot @vivekjoshi556, I will take a look first thing next week, now OOO.

2024-05-06 13:33 UTC, vivekjoshi556 commented
Hey @mman. Just wanted to check if you got some time to look at the PR.

2024-05-06 14:10 UTC, mman commented
@vivekjoshi556 The code looks nice and clean, the tests as well. Will try to deploy to my stage env later today.

2024-05-10 11:50 UTC, vivekjoshi556 commented
Hey @mman Just wanted to check in again.

@mtrezza if you have inputs as well, please let me know. 

There is a minor issue with linting I'll fix it in the next push, anything else let me know.

2024-05-10 12:55 UTC, mtrezza commented on src/Auth.js
> +function shouldUpdateSessionExpiry(config, session) {
```suggestion
/**
 * Checks whether session should be updated based on last update time & session length.
 */
function shouldUpdateSessionExpiry(config, session) {
```

2024-05-10 12:55 UTC, mtrezza commented on spec/Auth.spec.js
> +      let update = new Date();
```suggestion
      const update = new Date();
```

2024-05-10 12:58 UTC, mtrezza commented on src/Auth.js
> +}
Could you explain this logic?

2024-05-10 13:18 UTC, mtrezza commented
I wonder whether we need such a complex logic for this. If I understand https://github.com/parse-community/parse-server/issues/8981#issuecomment-1976147677 correctly, the purpose of this logic is to find a middle ground between:
- extending the session on every request --> con: high DB writes
- ensuring that the session extends before it expires --> con: session would never get extended

Wouldn't it be simpler to extend the session when the remaining session token validity time reached < 50% of the session length? 

For example:
- session length 1 year --> session extends if remaining time is < 182 days
- session length 1 day --> session extends if remaining time is < 12 hours
- session length 1 hour --> session extends if remaining time is < 30 mins
- session length 1 minute --> session extends if remaining time is < 30 secs

Pros:
- Simple to document and understand
- This adapts dynamically to the session length, instead of some arbitrary extension limits
- It's easy to make this configurable via a new Parse Server option in the future, by letting a developer configure the threshold, e.g. 50% as in example above.

2024-05-10 13:29 UTC, mtrezza requested changes

2024-05-10 13:29 UTC, mtrezza commented on spec/Auth.spec.js
> +    });
Please refactor by moving the loop into the test. We don't need a separate test entry for every param test. Considering https://github.com/parse-community/parse-server/pull/9113#issuecomment-2104597113, 1 simple test would be enough, not sure whether you need a loop at all here.

2024-05-14 22:51 UTC, mtrezza commented
@vivekjoshi556 Just a friendly ping here; if you could simplify these logic and add the functionality description to the option docs (this repo, not the docs repo), then we could go ahead and merge.

2024-05-15 10:11 UTC, vivekjoshi556 commented
So sorry just got a bit swamped with work. Give me some time

2024-05-27 03:24 UTC, vivekjoshi556 commented
@mtrezza I have made the mentioned changes. Please let me know if anything else needs to be done.

2024-05-27 14:12 UTC, mtrezza commented on src/Options/index.js
> +  /* Whether Parse Server should automatically extend a valid session by the sessionLength. The session will be extended when a request is received after half of the session's lifetime has passed.
```suggestion
  /* Whether Parse Server should automatically extend a valid session by the sessionLength. In order to reduce the number of session updates in the database, a session will only be extended when a request is received after at least half of the current session's lifetime has passed.
```

2024-05-27 14:13 UTC, mtrezza commented on src/Options/docs.js
> + * @property {Boolean} extendSessionOnUse Whether Parse Server should automatically extend a valid session by the sessionLength. The session will be extended when a request is received after half of
```suggestion
 * @property {Boolean} extendSessionOnUse Whether Parse Server should automatically extend a valid session by the sessionLength. In order to reduce the number of session updates in the database, a session will only be extended when a request is received after at least half of the current session's lifetime has passed.
```

2024-05-27 14:13 UTC, mtrezza commented on src/Options/Definitions.js
> +      "Whether Parse Server should automatically extend a valid session by the sessionLength. The session will be extended when a request is received after half of the session's lifetime has passed."
```suggestion
    help:
      "Whether Parse Server should automatically extend a valid session by the sessionLength. In order to reduce the number of session updates in the database, a session will only be extended when a request is received after at least half of the current session's lifetime has passed.",
```

2024-05-27 14:15 UTC, mtrezza approved these changes

2024-05-27 14:33 UTC, merged

2024-05-27 14:34 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-alpha.9](https://github.com/parse-community/parse-server/releases/tag/7.1.0-alpha.9)

2024-05-27 14:47 UTC, mman commented
@vivekjoshi556 Excellent, very clean code, putting into production :)

2024-06-30 02:03 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.1.0-beta.1)

2024-06-30 02:23 UTC, parseplatformorg commented
🎉 This change has been released in version [7.1.0](https://github.com/parse-community/parse-server/releases/tag/7.1.0)